# FROM node AS base
FROM node:18-alpine AS base
 
FROM base AS deps

WORKDIR /app


COPY package.json* package-lock.json* /app/
RUN npm install 

 
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules /app/node_modules
COPY . .
 

RUN npm run build
 

EXPOSE 3000

CMD ["npm", "start"]