version: '3.8'

services:
  nextapp:
    container_name: nextapp
    # image: nextimage
    build: 
      context: .
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:3000
    networks:
      - postgresnetwork
   
    # volumes:
    #  - ./nextf:/app
    #  - ./public:/app/public
    #  - ./next:/app

networks:
  postgresnetwork:
    external: true


    # "npm i axios cookie moment react-data-table-component react-js-pagination react-toastify --save"