FROM node:18-alpine

WORKDIR /app
 
COPY . /app

ENV PORT 3000

EXPOSE 3000

CMD ["npm", "start"]



# FROM node:18-alpine

# WORKDIR /app
 
# COPY . /app

# RUN npm install --production

# RUN npm run build

# # ENV PORT 3000

# EXPOSE 3000

# CMD ["npm", "start"]