version: '3.8'
services:
  jobpostgresql:
    image: postgres:14 
    container_name: jobpostgresql
    volumes:
      - jobpostgres:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
    networks:
      - postgresnetwork

  jobportalbackend:
    container_name: jobportalbackend
    build: 
      context: ./backend/core
      dockerfile: Dockerfile
    volumes:
    #  - ./static:/static
    #  - ./media:/media
     - ./backend/core:/app

    restart: always
    ports:
      - "8000:8000"
    networks:
      - postgresnetwork
    env_file: .env   
    depends_on:
      - jobpostgresql
      
  
  nextapp:
    container_name: nextapp
    build: 
      context: ./frontend
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:3000
    networks:
      - postgresnetwork
    depends_on:
    - jobportalbackend
  
 

   
    # volumes:
    #  - ./nextf:/app
    #  - ./public:/app/public
    #  - ./next:/app

 

    # "npm i axios cookie moment react-data-table-component react-js-pagination react-toastify --save"

 
 
networks:
  postgresnetwork:
    external: true
volumes:
  jobpostgres:
    external: true