
services:
  jobpostgresql:
    image: postgres:14 
    container_name: jobpostgresql
    volumes:
      - jobpostgres:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
 
  backend:
    container_name: backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
    #  - ./static:/static
    #  - ./media:/media
     - ./backend/core:/app
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    restart: always
    ports:
      - "8000:8000"
   
    env_file: .env   
    depends_on:
      - jobpostgresql
 
 
  nginx:
    restart: always
    container_name: nginx
    build: .
    ports:
      - "81:80"
 
    networks:
      - postgresnetwork



volumes:
  jobpostgres:
    external: true