version: '3.9'

services:


  nginx:
    container_name: nginx
    build: .

    ports:
      - 80:80
    networks:
      - postgresnetwork


volumes:
  static:
  node_modules:

networks:
  postgresnetwork:
    external: true