version: '3.9'

services:


  nginx:
    restart: always
    container_name: nginx
    build: .

    ports:
      - "80:80"
      - "443:443"
    networks:
      - postgresnetwork


volumes:
  static:
  node_modules:

networks:
  postgresnetwork:
    external: true